# Generated by Django 3.2.3 on 2021-05-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
