# Generated by Django 3.2.3 on 2021-06-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_alter_items_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item',
            field=models.CharField(max_length=100),
        ),
    ]
